config/routes.rb
Rails.application.routes.draw do
  resources :papers
  resources :events
  resources :articles
  resources :newsletters do
    resources :articles, only: [:index, :show, :new]
  end
  root to: 'application#welcome'
  devise_for :users, path: 'users', :controllers => {registrations: 'registrations', omniauth_callbacks: 'omniauth'},
  :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :unlock => 'unblock',
    :registration => 'profile',
    :sign_up => 'signup' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  belongs_to :user
  has_many :articles
  has_many :events

  validates :title, :sub_title, :date, :summary, presence: true
  validates :title, length: {minimum: 6}
  validates :summary, length: {minimum: 6}


  scope :my_newsletters, -> (id) {where(user_id: id) }

end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController

  def index
    if params[:user_id].present?
        @newsletters = Newsletter.my_newsletters(params[:user_id])
    else
        @newsletters = Newsletter.all
    end
  end

  def new
    @newsletter = Newsletter.new
  end

  def create
    @newsletter = current_user.newsletters.build(newsletter_params)
    @newsletter.user_id = current_user.id

    if @newsletter.save
      redirect_to @newsletter
    else
      render :new
    end
  end

  def show
    @newsletter = Newsletter.find_by_id(params[:id])
  end

  def edit
    @newsletter = Newsletter.find_by_id(params[:id])
  end

  def update
    @newsletter = Newsletter.find_by_id(params[:id])
    @newsletter.update(newsletter_params)
    redirect_to newsletter_path(@newsletter)
  end

  def destroy
    @newsletter = Newsletter.find_by_id(params[:id])
    @newsletter.destroy
    redirect_to newsletters_path
  end


  private
  def newsletter_params
    params.require(:newsletter).permit(:title, :sub_title, :summary, :date, :user_id)
  end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
  def newsletter_event_date
    @newsletter.date.strftime("%m/%d/%Y")
  end


end

app/views/newsletters/_form.html.erb
<%= form_for(@newsletter) do |f| %>

<div class="field">
  <%= f.label :title %><br/>
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :sub_title %><br/>
  <%= f.text_field :sub_title %>
</div>

<div class="field">
  <%= f.label :summary %><br/>
  <%= f.text_area :summary, cols: 30, rows: 10%>
</div>

<div class="field">
  <%= f.label :date %><br/>
  <%= f.date_field :date %>
</div>
<br>
<div class="vintage-container">
  <button class="button">Submit</button>

  <div class="loader">
    <div class="check">
      <span class="check-one"></span>
      <span class="check-two"></span>
    </div>
  </div>

</div>

<% end %>

app/views/newsletters/_nav.html.erb
<div class="sidenav">
  <%= link_to "New", new_newsletter_path %>
    <hr>
  <a href="#top">Back to top</a>
</div>

app/views/newsletters/edit.html.erb
<h3 class="retro-font-last">Newsletters</h3>
<%= render "form" %>

app/views/newsletters/index.html.erb
<%= render partial: "nav" %>
<div class="vintage__container">

  <%= form_tag "/newsletters", method: "GET" do %>
    <%= select_tag :user_id, options_from_collection_for_select(User.all, :id, :full_name), prompt: "Select a user" %>
    <%= submit_tag "Filter" %>
  <% end %>

  <% @newsletters.each do |n| %>
  <ul>
    * <%= n.title %> - <%= n.sub_title %> -
    <%= link_to "Review", newsletter_path(n.id) %> ||
    <%= link_to "Articles", newsletter_articles_path(n.id) %>
  </ul>

  <% end %>

  </div>

app/views/newsletters/new.html.erb
<h3 class="retro-font-last">Newsletters</h3>
<%= render "form" %>

app/views/newsletters/show.html.erb
  <h1><%= @newsletter.title %></h1>
  <h2><%= @newsletter.sub_title %></h2>
  <h3><%= newsletter_event_date %></h3>
  <p><%= @newsletter.summary %></p>
  

  <span class="retro-font-last"><%= link_to "Edit", edit_newsletter_path %> - </span>
  <span class="retro-font-last"><%= link_to "Delete", newsletter_path(@newsletter),
    :data => {:confirm => "Are you sure?",
    :method => "delete"} %></span>
  <h3 class="retro-font-last"><%= link_to "Add a new article", new_newsletter_article_path(@newsletter) %></h3>

  <h2>Articles in this newsletter</h2>

  <% @newsletter.articles.each do |article| %>
    <h3><%= link_to article.title, newsletter_article_path(@newsletter, article) %></h3>
  <% end %>