config/routes.rb
Rails.application.routes.draw do
  resources :papers
  resources :events
  resources :articles
  resources :newsletters do
    resources :articles, only: [:index, :show, :new]
  end
  root to: 'application#welcome'
  devise_for :users, path: 'users', :controllers => {registrations: 'registrations', omniauth_callbacks: 'omniauth'},
  :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :unlock => 'unblock',
    :registration => 'profile',
    :sign_up => 'signup' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/paper.rb
class Paper < ApplicationRecord
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  layout "paper"

  def index
    @newsletters = Newsletter.all
  end

  def show
    @newsletter = Newsletter.find_by_id(params[:id])
    @article = Article.find_by_id(params[:id])
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/index.html.erb
<% @newsletters.each do |n| %>
<ul style="text-align:center;">
  * <%= n.title %> - <%= n.sub_title %> -
  <%= link_to "Show", paper_path(n.id) %>
</ul>

<% end %>

app/views/papers/show.html.erb
<div class="head">
    <div class="headerobjectswrapper">
        <div class="weatherforcastbox"><span style="font-style: italic;">Repello Muggletum</span><br><span>This item is protected against muggle viewing</span><br>
          <span><%= link_to "Home", root_path %></span> || <span><%= link_to "Back", papers_path %></span></div>
        <header><%= @newsletter.title %></header>
    </div>

    <div class="subhead"><%= @newsletter.sub_title %> || <%= newsletter_event_date %></div>
</div>

<div class="content">
    <div class="collumns">
      <% @newsletter.articles.each do |n| %>
        <div class="collumn">

            <div class="head"><span class="headline hl3"><%= n.title %></span><p><span class="headline hl4">by <%= n.byline %></span></p></div>

            <% if n.photo.attached? %>
            <%= image_tag url_for(n.photo), :class => "media"%>
            <% else %>
            <h3></h3>
          <% end %>

            <p><%= n.body %></p></div>

        <% end %>
        <div class="collumn">
          </div>
        </div>
        </div>