config/routes.rb
Rails.application.routes.draw do
  resources :papers
  resources :events
  resources :articles
  resources :newsletters do
    resources :articles, only: [:index, :show, :new]
  end
  root to: 'application#welcome'
  devise_for :users, path: 'users', :controllers => {registrations: 'registrations', omniauth_callbacks: 'omniauth'},
  :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :unlock => 'unblock',
    :registration => 'profile',
    :sign_up => 'signup' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<div class="sticky">
  <div class="back">
    <%= image_tag("ribbonfinal.png", :alt => "ribbon", style: "width:100%") %>
  </div>
  <div id="menu-outer" style="text-align: center;" >
    <div class="table">
      <ul id="horizontal-list">
        <% if user_signed_in? %>

        <li class="retro-font"><%= link_to "Home", root_path %></li>

          <!-- Newsletters Drop Down -->
          <div class="dropdown">
            <li class="retro-font"><%= link_to "Content", newsletters_path %></li>
            <div class="dropdown-content">
                <li class="drop"><%= link_to "Newsletters", newsletters_path %></li>
              <li class="drop"><%= link_to "Articles", articles_path %></li>
              <li class="drop"><%= link_to "Events", events_path %></li>
              <!-- Announcements -->
              <!-- Ads -->
            </div>
          </div>

          <div class="dropdown">
            <li class="retro-font"><%= link_to "Profile", edit_user_registration_path %></li>
            <div class="dropdown-content">
              <li class="drop"><%= link_to "Edit", edit_user_registration_path %></li>
              <li class="drop"><%= link_to "Logout", destroy_user_session_path, method: "delete" %></li>
              <!-- ??? -->
            </div>
          </div>
          <li class="retro-font-last"><%= link_to "Paper", papers_path %></li>


        <% else %>
          <li class="retro-font"><%= link_to "New User", new_user_registration_path %></li>
          <li class="retro-font-last"><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HpDailyProphet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Satisfy"
    href="https://fonts.googleapis.com/css?family=Six+Caps">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>

      body {
        font-family: 'Shadows Into Light', cursive;
        font-size: 22px;

    </style>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="halo"></div>
    <%= yield %>

  </body>
</html>

app/views/layouts/paper.html.erb
<html>
<head>
    <link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900,400italic,700italic,900italic|Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="styles/newspaper.css">
    <title>Newspaper</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

<style>

  body{
      font-family: 'Droid Serif', serif;
      font-size: 14px;
      color: #2f2f2f;
      background-color: #f9f7f1;
  }
  header{
      font-family: 'Playfair Display', serif;
      font-weight: 900;
      font-size: 80px;
      text-transform: uppercase;
      display: inline-block;
      line-height: 72px;
      margin-bottom: 20px;

  }
  p{
      margin-top: 0;
      margin-bottom: 20px;
  }
  .head{
      text-align: center;
      position: relative;


  }

  .headerobjectswrapper{
  }

  .subhead{
      text-transform: uppercase;
      border-bottom: 2px solid #2f2f2f;
      border-top: 2px solid #2f2f2f;
      padding: 12px 0 12px 0;

  }
  .weatherforcastbox{
      position: relative;
      width: 12%;
      left: 10px;
      border: 3px double #2f2f2f;
      padding: 10px 15px 10px 15px;
      line-height: 20px;
      display: inline-block;
      margin: 0 50px 20px -360px;
  }
  .content{
      font-size: 0;
      line-height: 0;
      word-spacing: -.31em;
      display: inline-block;
      margin: 30px 2% 0 2%;


  }
  .collumns{

  }

  .collumn{
      font-size: 14px;
      line-height: 20px;
      width: 17.5%;
      display: inline-block;
      padding: 0 1% 0 1%;
      vertical-align: top;
      margin-bottom: 50px;
      transition: all .7s;
  }
  .collumn + .collumn {
    border-left: 1px solid #2f2f2f;
  }
  .collumn .headline{
      text-align: center;
      line-height: normal;
      font-family: 'Playfair Display', serif;
      display: block;
      margin: 0 auto;


  }
  .collumn .headline.hl1{
      font-weight: 700;
      font-size: 30px;
      text-transform: uppercase;
      padding: 10px 0 10px 0;

  }

  .collumn .headline.hl2{
      font-weight: 400;
      font-style: italic;
      font-size: 24px;
      box-sizing: border-box;
      padding: 10px 0 10px 0;
  }

  .collumn .headline.hl2:before{
      border-top: 1px solid #2f2f2f;
      content: '';
      width: 100px;
      height: 7px;
      display: block;
      margin: 0 auto;
  }
  .collumn .headline.hl2:after{
      border-bottom: 1px solid #2f2f2f;
      content: '';
      width: 100px;
      height: 13px;
      display: block;
      margin: 0 auto;

  }

  .collumn .headline.hl3{
      font-weight: 400;
      font-style: italic;
      font-size: 36px;
      box-sizing: border-box;
      padding: 10px 0 10px 0;
  }
  .collumn .headline.hl4{
      font-weight: 700;
      font-size: 12px;
      box-sizing: border-box;
      padding: 10px 0 10px 0;
  }
  .collumn .headline.hl4:before{
      border-top: 1px solid #2f2f2f;
      content: '';
      width: 100px;
      height: 7px;
      display: block;
      margin: 0 auto;
  }
  .collumn .headline.hl4:after{
      border-bottom: 1px solid #2f2f2f;
      content: '';
      width: 100px;
      height: 10px;
      display: block;
      margin: 0 auto;

  }

  .collumn .headline.hl5{
      font-weight: 400;
      font-size: 42px;
      text-transform: uppercase;
      font-style: italic;
      box-sizing: border-box;
      padding: 10px 0 10px 0;
  }
  .collumn .headline.hl6{
      font-weight: 400;
      font-size: 18px;
      box-sizing: border-box;
      padding: 10px 0 10px 0;
  }
  .collumn .headline.hl6:before{
      border-top: 1px solid #2f2f2f;
      content: '';
      width: 100px;
      height: 7px;
      display: block;
      margin: 0 auto;
  }
  .collumn .headline.hl6:after{
      border-bottom: 1px solid #2f2f2f;
      content: '';
      width: 100px;
      height: 10px;
      display: block;
      margin: 0 auto;

  }
  .collumn .headline.hl7{
      font-weight: 700;
      font-size: 12px;
      box-sizing: border-box;
      display: block;
      padding: 10px 0 10px 0;
  }
  .collumn .headline.hl8{
      font-weight: 700;
      font-size: 12px;
      box-sizing: border-box;
      padding: 10px 0 10px 0;
  }
  .collumn .headline.hl9{
      font-weight: 700;
      font-size: 12px;
      box-sizing: border-box;
      padding: 10px 0 10px 0;
  }
  .collumn .headline.hl10{
      font-weight: 700;
      font-size: 12px;
      box-sizing: border-box;
      padding: 10px 0 10px 0;
  }
  .collumn .citation{
      font-family: 'Playfair Display', serif;
      font-size: 36px;
      line-height: 44px;
      /*font-style: italic;*/
      text-align: center;
      font-weight: 400;
      display: block;
      margin: 40px 0 40px 0;
      font-feature-settings: "liga", "dlig";

  }
  .collumn .citation:before{
      border-top: 1px solid #2f2f2f;
      content: '';
      width: 100px;
      height: 16px;
      display: block;
      margin: 0 auto;
  }
  .collumn .citation:after{
      border-bottom: 1px solid #2f2f2f;
      content: '';
      width: 100px;
      height: 16px;
      display: block;
      margin: 0 auto;
  }
  .collumn .figure {
  	  margin: 0 0 20px;
  }
  .collumn .figcaption{
  	font-style: italic;
  	font-size: 12px;
  }
  .media {
      -webkit-filter: sepia(80%) contrast(1) opacity(0.8);
      filter: sepia(80%) grayscale(1) contrast(1) opacity(0.8);
      mix-blend-mode: multiply;
      width: 100%;
  }
  /*________________________________________________________________________________________________________________________________*/
  /*MEDIAQUERIES*/
  @media only all and (max-width: 1300px) {
      .weatherforcastbox{
          display: none;
      }

  }
  @media only all and (max-width: 1200px) {
      .collumn{
          width: 31%;
      }

  }
      @media only all and (max-width: 900px) {
      .collumn{
          width: 47%;
      }

  }
  @media only all and (max-width: 600px) {
      .collumn{
          width: 100%;
      }
  	.collumn + .collumn {
  				border-left: none;
        	border-bottom: 1px solid #2f2f2f;
  	}
      header{
          max-width: 320px;
          font-size: 60px;
          line-height: 54px;
          overflow: hidden;
      }

  }

</style>

</head>
<body>
<%= yield %>

</body>
</html>